Atulgera/mobile responsiveness for graphic
RivalryIssue/rivalryissue.github.io pull request #3
Opened 2021-11-14 16:19 UTC by atulgera02

2021-11-14 18:04 UTC, parthd4 approved these changes
Excellent! Just a few comments, but nice work 🔥

2021-11-14 18:32 UTC, parthd4 requested changes
Sorry - i noticed some other things. We should still render a bar if we have <1,000 dollars raised. And I would expect the bar to be left-aligned instead of center: 
![image](https://user-images.githubusercontent.com/25800753/141693826-7c234acb-ed64-42e5-8119-1943c6a905fe.png)

2021-11-14 18:32 UTC, parthd4 commented on src/js/components/DonationGraphic.jsx
> +    let str_array = value.slice(1).split(",");
What happens when `value` is less than a thousand like `$100` and so it has no commas? We should still show the bar being filled `1%` in this case.

2021-11-14 18:33 UTC, parthd4 commented on src/js/components/DonationGraphic.jsx
> +    let str_array = value.slice(1).split(",");
It might be easier if the scraper stores floats in the `data.json` and we convert them to strings and add commas where necessary on the FE

2021-11-14 22:56 UTC, rimazmk commented on src/js/components/DonationGraphic.jsx
> +    let str_array = value.slice(1).split(",");
Changes should be addressed now -- gonna skip on the last suggestion since the parsing is already done on the FE :/

2021-11-15 02:05 UTC, parthd4 approved these changes

2021-11-15 02:06 UTC, merged